## Download Bitcoin data from Binance

In [17]:
import requests
import json
import time

# Set the start and end times for the API calls
start_time = 1535760000000 # September 1st, 2018 in Unix timestamp format
end_time =   1682765212000 # Today

# Set the symbol and interval for the API calls
symbol = 'BTCUSDT'
interval = '1d'

# Create an empty list to store the results
results = []

calls = 0

# Loop through the time range in 1 week intervals and call the API
while start_time < end_time:
    calls += 1
    
    # Build the API endpoint URL
    url = f'https://api.binance.com/api/v3/klines?symbol={symbol}&interval={interval}&startTime={start_time}&endTime={start_time + (86400 * 7 * 26 * 1000)}'

    # Make the API call
    response = requests.get(url)

    # Parse the JSON response and append the results to the list
    results += json.loads(response.text)

    # Increment the start time by 26 weeks (half a year)
    start_time += 86400 * 7 * 26 * 1000
    
    print(calls)

    # Pause for 1 second between API calls to avoid rate limiting
    time.sleep(1)

# Write the concatenated results to a file
with open('binance_data.json', 'w') as f:
    json.dump(results, f)

1
2
3
4
5
6
7
8
9
10

In [20]:
url = f'https://api.binance.com/api/v3/klines?symbol={symbol}&interval={interval}&startTime={start_time}&endTime={start_time + (86400 * 7 * 26 * 1000)}'
display(requests.get(url).text)

'[]'

In [19]:
import pandas as pd

pd.read_json('binance_data.json')

,0,1,2,3,4,5,6,7,8,9,10,11
0,1535760000000,7011.21,7275.00,7008.74,7200.01,40323.414093,1535846399999,2.872993e+08,217286,22552.716145,1.606678e+08,0
1,1535846400000,7201.57,7345.45,7127.00,7302.01,39814.840352,1535932799999,2.885260e+08,210282,22422.520630,1.625237e+08,0
2,1535932800000,7302.00,7338.28,7191.63,7263.02,32396.018371,1536019199999,2.353936e+08,173846,16914.880588,1.229179e+08,0
3,1536019200000,7263.00,7410.00,7227.17,7359.06,35300.640518,1536105599999,2.589784e+08,183178,19983.177591,1.466194e+08,0
4,1536105600000,7359.05,7397.30,6682.00,6700.00,63715.256267,1536191999999,4.494635e+08,308813,31531.579021,2.227200e+08,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1706,1682380800000,27510.93,28399.99,27192.00,28300.79,52325.146370,1682467199999,1.446329e+09,1087067,26833.471920,7.420692e+08,0
1707,1682467200000,28300.80,30036.00,27235.00,28415.29,129228.404030,1682553599999,3.719701e+09,2261942,64540.555210,1.857698e+09,0
1708,1682553600000,28415.29,29890.00,28378.86,29472.77,95430.824310,1682639999999,2.784860e+09,1990148,48601.974740,1.418439e+09,0
1709,1682640000000,29472.77,29599.54,28891.00,29311.70,54298.165780,1682726399999,1.590684e+09,1129240,26659.216400,7.807849e+08,0
1710,1682726400000,29311.69,29448.88,29195.58,29253.00,10296.820890,1682812799999,3.019546e+08,296864,5120.729450,1.501745e+08,0